/* SYNTHNET - sw.js
 * Cache-first service worker. Precaches the shell, then caches every
 * successful same-origin GET so visited sites keep working offline.
 *
 * CACHE_VERSION below is GENERATED by tools/build.py -- a hash of the shell
 * files and every site.json. Do not edit it by hand; run the build. It was
 * the literal string 'synthnet-v1' from the first commit of this project
 * until it was generated, and since a cache hit is served forever and the
 * cache is only ever dropped when this name changes, that meant a browser
 * which had opened the app once kept serving the build it first saw.
 */
'use strict';

var CACHE_VERSION = 'synthnet-256c3095ec69';

var SHELL = [
  './',
  './index.html',
  './manifest.webmanifest',
  './theme/aero.css',
  './theme/live.css',
  './theme/compose.css',
  './theme/feeds.css',
  './app/markup.js',
  './app/loadmap.js',
  './app/render.js',
  './app/live.js',
  './app/liveui.js',
  './app/grammar.js',
  './app/tick.js',
  './app/store.js',
  './app/me.js',
  './app/packs.js',
  './app/alerts.js',
  './app/feedsui.js',
  './app/hostbridge.js',
  './app/bots.js',
  './app/fame.js',
  './app/compose.js',
  './app/slop_social.js',
  './app/slop_forum.js',
  './app/slop_ads.js',
  './app/slop_news.js',
  './app/engine.js',
  './theme/skins/aggregator.css',
  './app/types/aggregator.js',
  './theme/skins/assistant.css',
  './app/types/assistant.js',
  './theme/skins/blog.css',
  './app/types/blog.js',
  './theme/skins/board.css',
  './app/types/board.js',
  './theme/skins/chat.css',
  './app/types/chat.js',
  './theme/control.css',
  './app/control.js',
  './theme/skins/dash.css',
  './app/types/dash.js',
  './theme/skins/forum.css',
  './app/types/forum.js',
  './theme/skins/mail.css',
  './app/types/mail.js',
  './theme/skins/market.css',
  './app/types/market.js',
  './theme/skins/media.css',
  './app/types/media.js',
  './theme/skins/news.css',
  './app/types/news.js',
  './theme/skins/newsletter.css',
  './app/types/newsletter.js',
  './theme/skins/page.css',
  './app/types/page.js',
  './theme/skins/portal.css',
  './app/types/portal.js',
  './theme/skins/qa.css',
  './app/types/qa.js',
  './theme/skins/shop.css',
  './app/types/shop.js',
  './theme/skins/social.css',
  './app/types/social.js',
  './theme/skins/stream.css',
  './app/types/stream.js',
  './theme/skins/wiki.css',
  './app/types/wiki.js',
  './theme/skins/wire.css',
  './app/types/wire.js',
  './net/registry.json',
  './net/search.json'
];

self.addEventListener('install', function (event) {
  event.waitUntil(
    caches.open(CACHE_VERSION).then(function (cache) {
      /* Add each entry on its own so one missing optional file (a theme
         variant, a manifest spelling) cannot fail the whole install. */
      return Promise.all(SHELL.map(function (url) {
        return cache.add(new Request(url, { cache: 'reload' })).catch(function () {
          return cache.add(url).catch(function () { return null; });
        });
      }));
    }).then(function () {
      return self.skipWaiting();
    }).catch(function () {
      return self.skipWaiting();
    })
  );
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (key) {
        if (key !== CACHE_VERSION) return caches.delete(key);
        return null;
      }));
    }).then(function () {
      return self.clients.claim();
    }).catch(function () { return null; })
  );
});

self.addEventListener('fetch', function (event) {
  var req = event.request;
  if (!req || req.method !== 'GET') return;

  var sameOrigin = false;
  try {
    sameOrigin = (new URL(req.url).origin === self.location.origin);
  } catch (e) {
    sameOrigin = false;
  }

  event.respondWith(
    caches.match(req, { ignoreSearch: false }).then(function (hit) {
      if (hit) return hit;

      return fetch(req).then(function (res) {
        if (sameOrigin && res && res.ok && (res.type === 'basic' || res.type === 'default')) {
          var copy = res.clone();
          caches.open(CACHE_VERSION).then(function (cache) {
            return cache.put(req, copy);
          }).catch(function () { return null; });
        }
        return res;
      }).catch(function () {
        if (req.mode === 'navigate') {
          return caches.match('./index.html').then(function (shell) {
            return shell || new Response(
              'Offline and this page was never cached.',
              { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } }
            );
          });
        }
        return caches.match(req, { ignoreSearch: true }).then(function (loose) {
          return loose || new Response(
            'Offline and this resource was never cached.',
            { status: 504, headers: { 'Content-Type': 'text/plain; charset=utf-8' } }
          );
        });
      });
    })
  );
});

self.addEventListener('message', function (event) {
  if (event && event.data === 'synth-skip-waiting') self.skipWaiting();
});
