/* SYNTHNET - app/engine.js
 * SYNTH.data (registry + site loading) and SYNTH.engine (router, tabs,
 * history, address bar, search, start page, status bar, keyboard).
 * Classic script, boots on DOMContentLoaded. No modules, no network,
 * no innerHTML for anything that came out of a site.json.
 */
window.SYNTH = window.SYNTH || {};
(function () {
  'use strict';

  var SYNTH = window.SYNTH;

  var HOME_DOMAIN = 'start.verity.net';
  var SEARCH_DOMAIN = 'search.verity.net';
  var FEEDS_DOMAIN = 'feeds.verity.net';
  var HOME_URL = 'synth://start.verity.net/';
  var BROWSER_NAME = 'Verity Explorer';
  var MAX_STACK = 120;

  function el() { return SYNTH.el.apply(null, arguments); }
  function byId(id) { return document.getElementById(id); }
  function hasOwn(o, k) { return o && Object.prototype.hasOwnProperty.call(o, k); }

  function clearNode(node) {
    if (!node) return;
    while (node.firstChild) node.removeChild(node.firstChild);
  }

  function truncate(s, n) {
    s = String(s === null || s === undefined ? '' : s);
    return s.length > n ? s.slice(0, n - 1) + '…' : s;
  }

  function closestTag(node, tag) {
    tag = tag.toUpperCase();
    while (node && node !== document) {
      if (node.nodeType === 1 && node.tagName === tag) return node;
      node = node.parentNode;
    }
    return null;
  }

  /* ================================================================== */
  /* DATA                                                                */
  /* ================================================================== */

  var siteCache = {};       /* domain -> site|null */
  var registryPromise = null;
  var searchPromise = null;

  function embedded() {
    return (typeof window.SYNTH_EMBEDDED === 'object' && window.SYNTH_EMBEDDED) ? window.SYNTH_EMBEDDED : null;
  }

  function fetchJSON(url) {
    if (typeof window.fetch !== 'function') return Promise.resolve(null);
    try {
      return window.fetch(url).then(function (res) {
        if (!res || !res.ok) return null;
        return res.json().then(function (j) { return j; }, function () { return null; });
      }, function () { return null; });
    } catch (e) {
      return Promise.resolve(null);
    }
  }

  function loadRegistry() {
    if (registryPromise) return registryPromise;
    var emb = embedded();
    if (emb && emb.registry) {
      SYNTH.data.registry = emb.registry;
      registryPromise = Promise.resolve(emb.registry);
      return registryPromise;
    }
    registryPromise = fetchJSON('./net/registry.json').then(function (r) {
      SYNTH.data.registry = r || null;
      return SYNTH.data.registry;
    });
    return registryPromise;
  }

  function registryList() {
    var arr = registryListBuiltIn();
    if (!SYNTH.packs) return arr;

    /* Pack sites join the directory and the search index. Same domain means
     * replace, not duplicate -- two entries for one address would show up as
     * a ghost in the start page listing. */
    var extra = SYNTH.packs.registryRows();
    if (!extra.length) return arr;
    var byDomain = {};
    arr.forEach(function (row) { if (row && row.domain) byDomain[String(row.domain).toLowerCase()] = row; });
    extra.forEach(function (row) { byDomain[String(row.domain).toLowerCase()] = row; });
    var out = [];
    for (var d in byDomain) {
      if (hasOwn(byDomain, d)) out.push(byDomain[d]);
    }
    return out;
  }

  function registryListBuiltIn() {
    var r = SYNTH.data.registry;
    var arr = [];
    var k, v;
    if (!r) return arr;
    if (Array.isArray(r)) arr = r.slice();
    else if (Array.isArray(r.sites)) arr = r.sites.slice();
    else if (r.sites && typeof r.sites === 'object') {
      for (k in r.sites) {
        if (!hasOwn(r.sites, k)) continue;
        v = r.sites[k];
        if (v && typeof v === 'object') {
          if (!v.domain) { v = shallow(v); v.domain = k; }
          arr.push(v);
        }
      }
    } else {
      for (k in r) {
        if (!hasOwn(r, k)) continue;
        v = r[k];
        if (v && typeof v === 'object' && (v.domain || v.type)) {
          if (!v.domain) { v = shallow(v); v.domain = k; }
          arr.push(v);
        }
      }
    }
    var out = [];
    for (var i = 0; i < arr.length; i++) {
      if (arr[i] && arr[i].domain) out.push(arr[i]);
    }
    return out;
  }

  function shallow(o) {
    var c = {};
    for (var k in o) if (hasOwn(o, k)) c[k] = o[k];
    return c;
  }

  function registryEntry(domain) {
    var list = registryList();
    for (var i = 0; i < list.length; i++) {
      if (String(list[i].domain).toLowerCase() === domain) return list[i];
    }
    return null;
  }

  function slugFor(domain, entry) {
    if (entry && entry.slug) return String(entry.slug);
    /* registry.json (generated by tools/build.py) carries the real on-disk
       location as "path"; the folder may have a suffix the domain does not. */
    if (entry && entry.path) {
      var m = String(entry.path).match(/net\/sites\/([^\/]+)\/site\.json$/);
      if (m) return m[1];
    }
    return String(domain).replace(/\./g, '-');
  }

  function getSite(domain) {
    domain = String(domain || '').toLowerCase().trim();
    if (!domain) return Promise.resolve(null);
    if (hasOwn(siteCache, domain)) return Promise.resolve(siteCache[domain]);

    /* Imported packs and sites you authored win over anything built in, so a
     * pack can replace a shipped site by reusing its domain. Checked before
     * the cache is populated, and the cache is dropped on import. */
    if (SYNTH.packs) {
      var over = SYNTH.packs.overlay();
      if (hasOwn(over, domain)) {
        siteCache[domain] = over[domain];
        return Promise.resolve(siteCache[domain]);
      }
    }

    var emb = embedded();
    if (emb && emb.sites && typeof emb.sites === 'object') {
      var s = hasOwn(emb.sites, domain) ? emb.sites[domain] : null;
      siteCache[domain] = s || null;
      return Promise.resolve(siteCache[domain]);
    }

    return loadRegistry().then(function () {
      var slug = slugFor(domain, registryEntry(domain));
      return fetchJSON('./net/sites/' + encodeURIComponent(slug) + '/site.json');
    }).then(function (site) {
      if (site && typeof site === 'object') {
        if (!site.domain) site.domain = domain;
        siteCache[domain] = site;
      } else {
        siteCache[domain] = null;
      }
      return siteCache[domain];
    }, function () {
      siteCache[domain] = null;
      return null;
    });
  }

  SYNTH.data = {
    registry: null,
    getSite: getSite,
    loadRegistry: loadRegistry,
    list: registryList,
    entry: registryEntry,
    forget: function (domain) {
      domain = String(domain || '').toLowerCase();
      if (hasOwn(siteCache, domain)) delete siteCache[domain];
    },

    /* Called by SYNTH.packs after an import, a toggle or a delete. Without
     * this the new sites would not appear until the app was restarted,
     * because both the registry and each loaded site are cached. */
    invalidate: function () {
      siteCache = {};
      searchPromise = null;
    }
  };

  /* ================================================================== */
  /* URL RESOLUTION                                                      */
  /* ================================================================== */

  function decodeSeg(s) {
    try { return decodeURIComponent(s); } catch (e) { return s; }
  }

  function parseQuery(qs) {
    var out = {};
    if (!qs) return out;
    var parts = String(qs).split('&');
    for (var i = 0; i < parts.length; i++) {
      if (!parts[i]) continue;
      var eq = parts[i].indexOf('=');
      var k = eq === -1 ? parts[i] : parts[i].slice(0, eq);
      var v = eq === -1 ? '' : parts[i].slice(eq + 1);
      k = decodeSeg(k.replace(/\+/g, ' '));
      v = decodeSeg(v.replace(/\+/g, ' '));
      if (k) out[k] = v;
    }
    return out;
  }

  function resolve(href, currentDomain) {
    var raw = String(href === null || href === undefined ? '' : href).trim();
    while (raw.charAt(0) === '#') raw = raw.slice(1);

    var absolute = false;
    if (/^synth:\/\//i.test(raw)) { raw = raw.replace(/^synth:\/\//i, ''); absolute = true; }
    else if (raw.slice(0, 2) === '//') { raw = raw.slice(2); absolute = true; }
    else if (raw.charAt(0) !== '/' && raw !== '') {
      var head = raw.split('/')[0].split('?')[0];
      if (head.indexOf('.') !== -1) absolute = true;
    }

    var domain, pathPart;
    if (absolute) {
      var slash = raw.indexOf('/');
      var qm = raw.indexOf('?');
      var cut;
      if (slash === -1 && qm === -1) cut = raw.length;
      else if (slash === -1) cut = qm;
      else if (qm === -1) cut = slash;
      else cut = Math.min(slash, qm);
      domain = raw.slice(0, cut).toLowerCase();
      pathPart = raw.slice(cut) || '/';
    } else {
      domain = String(currentDomain || '').toLowerCase();
      pathPart = raw.charAt(0) === '/' ? raw : ('/' + raw);
    }

    var hi = pathPart.indexOf('#');
    if (hi !== -1) pathPart = pathPart.slice(0, hi);

    var qs = '';
    var qi = pathPart.indexOf('?');
    if (qi !== -1) { qs = pathPart.slice(qi + 1); pathPart = pathPart.slice(0, qi); }

    var rawSegs = pathPart.split('/');
    var path = [];
    for (var i = 0; i < rawSegs.length; i++) {
      if (rawSegs[i] === '' || rawSegs[i] === '.') continue;
      path.push(decodeSeg(rawSegs[i]));
    }

    return { domain: domain, path: path, query: parseQuery(qs) };
  }

  function formatLoc(loc) {
    var s = 'synth://' + (loc.domain || '');
    var segs = [];
    for (var i = 0; i < (loc.path || []).length; i++) segs.push(encodeURIComponent(loc.path[i]));
    s += '/' + segs.join('/');
    var keys = [];
    for (var k in (loc.query || {})) if (hasOwn(loc.query, k)) keys.push(k);
    if (keys.length) {
      var q = [];
      for (var j = 0; j < keys.length; j++) {
        q.push(encodeURIComponent(keys[j]) + '=' + encodeURIComponent(loc.query[keys[j]]));
      }
      s += '?' + q.join('&');
    }
    return s;
  }

  function searchUrl(q) {
    return 'synth://' + SEARCH_DOMAIN + '/?q=' + encodeURIComponent(String(q || ''));
  }

  /* ================================================================== */
  /* CHROME ELEMENTS                                                     */
  /* ================================================================== */

  var ui = {};

  function pick() {
    for (var i = 0; i < arguments.length; i++) {
      var found = null;
      var sel = arguments[i];
      if (sel.charAt(0) === '#') found = byId(sel.slice(1));
      else found = document.querySelector(sel);
      if (found) return found;
    }
    return null;
  }

  function ensureViewport() {
    if (ui.viewport && ui.viewport.parentNode) return ui.viewport;
    ui.viewport = pick('#synth-viewport', '.synth-viewport');
    if (!ui.viewport) {
      ui.viewport = el('div', { id: 'synth-viewport', class: 'synth-viewport' });
      document.body.appendChild(ui.viewport);
    }
    return ui.viewport;
  }

  function ensureTabStrip() {
    if (ui.tabstrip && ui.tabstrip.parentNode) return ui.tabstrip;
    ui.tabstrip = pick('#synth-tabs', '#synth-tabstrip', '.synth-tabs', '.synth-tabstrip');
    if (!ui.tabstrip) {
      ui.tabstrip = el('div', { id: 'synth-tabs', class: 'synth-tabs' });
      var vp = ensureViewport();
      if (vp.parentNode) vp.parentNode.insertBefore(ui.tabstrip, vp);
      else document.body.appendChild(ui.tabstrip);
    }
    return ui.tabstrip;
  }

  function ensureStatus() {
    if (ui.status && ui.status.parentNode) return ui.status;
    ui.status = pick('#synth-status', '#synth-statusbar', '.synth-status', '.synth-statusbar');
    if (!ui.status) {
      ui.status = el('div', { id: 'synth-status', class: 'synth-status' });
      document.body.appendChild(ui.status);
    }
    return ui.status;
  }

  function setStatus(msg) {
    var s = ensureStatus();
    if (!s) return;
    var target = s.querySelector ? (s.querySelector('.synth-status-text') || s) : s;
    clearNode(target);
    target.appendChild(document.createTextNode(String(msg === null || msg === undefined ? '' : msg)));
  }

  function setAddress(url) {
    var a = ui.address;
    if (!a) return;
    if ('value' in a) a.value = url;
    else { clearNode(a); a.appendChild(document.createTextNode(url)); }
  }

  function setProgress(on) {
    var p = ui.progress;
    if (!p) return;
    if (on) p.className = (p.className.replace(/\s*\bactive\b/g, '') + ' active').replace(/^\s+/, '');
    else p.className = p.className.replace(/\s*\bactive\b/g, '');
    p.setAttribute('aria-busy', on ? 'true' : 'false');
    if (on) p.setAttribute('data-loading', '1'); else p.removeAttribute('data-loading');
    var bar = p.querySelector ? p.querySelector('.bar, .synth-progress-bar, i, b, span, div') : null;
    if (bar && bar.style) bar.style.width = on ? '70%' : '0%';
  }

  function updateNavButtons() {
    var t = currentTab();
    var setDis = function (node, disabled) {
      if (!node) return;
      if (disabled) {
        node.setAttribute('disabled', 'disabled');
        node.className = (node.className.replace(/\s*\bdisabled\b/g, '') + ' disabled').replace(/^\s+/, '');
      } else {
        node.removeAttribute('disabled');
        node.className = node.className.replace(/\s*\bdisabled\b/g, '');
      }
    };
    setDis(ui.back, !t || !t.back.length);
    setDis(ui.forward, !t || !t.fwd.length);
  }

  /* built-in page styling: chrome we author ourselves, kept scoped so it
     cannot leak into site skins. */
  var BUILTIN_CSS = [
    '.synth-builtin{font:12px Tahoma,"Segoe UI",Verdana,Geneva,sans-serif;color:#101010;background:#fff;}',
    '.synth-builtin a{color:#0b3d91;text-decoration:underline;cursor:pointer;}',
    '.synth-builtin a:visited{color:#551a8b;}',
    '.synth-b-head{background:linear-gradient(#f2f7fe,#ccdff6);border-bottom:1px solid #93b2da;padding:10px 14px;}',
    '.synth-b-title{font-size:20px;font-weight:bold;color:#1b3f78;letter-spacing:-0.5px;}',
    '.synth-b-sub{color:#46586f;font-size:11px;margin-top:2px;}',
    '.synth-b-body{padding:12px 14px 24px;}',
    '.synth-b-form{margin:8px 0 14px;}',
    '.synth-b-form input[type=text]{border:1px solid #7a9bc4;padding:3px 4px;font:12px Tahoma,sans-serif;width:340px;max-width:58%;background:#fff;}',
    '.synth-b-form button{border:1px solid #7a9bc4;background:linear-gradient(#ffffff,#dde8f6);padding:3px 12px;font:12px Tahoma,sans-serif;cursor:pointer;margin-left:4px;}',
    '.synth-b-group{margin:0 0 14px;border:1px solid #c3d2e8;background:#fff;}',
    '.synth-b-group h2{margin:0;font-size:12px;padding:4px 8px;background:linear-gradient(#dcebfb,#b6cdee);border-bottom:1px solid #93b2da;color:#1b3f78;}',
    '.synth-b-item{padding:6px 9px;border-bottom:1px solid #eef2f8;}',
    '.synth-b-item:last-child{border-bottom:none;}',
    '.synth-b-item .nm{font-weight:bold;}',
    '.synth-b-item .dm{color:#217821;font-size:11px;margin-left:6px;}',
    '.synth-b-item .ds{color:#333;display:block;margin-top:2px;}',
    '.synth-b-count{color:#555;margin:0 0 14px;border-bottom:1px solid #e2e2e2;padding-bottom:6px;}',
    '.synth-b-result{margin:0 0 15px;max-width:740px;}',
    '.synth-b-result .t{font-size:14px;}',
    '.synth-b-result .u{color:#217821;font-size:11px;}',
    '.synth-b-result .s{color:#222;margin-top:1px;}',
    '.synth-b-err{max-width:620px;padding:16px 18px;}',
    '.synth-b-err h1{font-size:17px;margin:0 0 10px;color:#000;}',
    '.synth-b-err ul{margin:8px 0 10px 20px;padding:0;}',
    '.synth-b-err li{margin:2px 0;}',
    '.synth-b-rule{border-top:1px solid #d8d8d8;margin:12px 0;}',
    '.synth-b-note{background:#ffffe1;border:1px solid #d4c97a;padding:9px 10px;margin:10px 0;}',
    '.synth-b-foot{color:#6a6a6a;font-size:11px;margin-top:18px;border-top:1px solid #e2e2e2;padding-top:6px;}'
  ].join('\n');

  function injectBuiltinCSS() {
    if (byId('synth-builtin-css')) return;
    var st = document.createElement('style');
    st.id = 'synth-builtin-css';
    st.setAttribute('type', 'text/css');
    st.appendChild(document.createTextNode(BUILTIN_CSS));
    (document.head || document.documentElement).appendChild(st);
  }

  /* ================================================================== */
  /* TABS + HISTORY                                                      */
  /* ================================================================== */

  var tabs = [];
  var activeIndex = 0;
  var tabSeq = 1;
  var navToken = 0;
  var suppressHash = 0;

  function newTabObj() {
    return { id: 't' + (tabSeq++), url: null, domain: HOME_DOMAIN, title: 'New Tab', back: [], fwd: [] };
  }

  function currentTab() {
    if (!tabs.length) { tabs.push(newTabObj()); activeIndex = 0; }
    if (activeIndex < 0 || activeIndex >= tabs.length) activeIndex = tabs.length - 1;
    return tabs[activeIndex];
  }

  function renderTabs() {
    var strip = ensureTabStrip();
    if (!strip) return;
    var newBtn = byId('synth-newtab');
    var keepNew = (newBtn && newBtn.parentNode === strip) ? newBtn : null;
    var kids = [];
    for (var c = 0; c < strip.childNodes.length; c++) kids.push(strip.childNodes[c]);
    for (var d = 0; d < kids.length; d++) {
      if (kids[d] !== keepNew) strip.removeChild(kids[d]);
    }

    tabs.forEach(function (t, i) {
      /* 'synth-tabclose', not 'synth-tab-close': the stylesheet spells it
       * without the second hyphen (theme/aero.css:739), and for a long time
       * this emitted the other spelling, so every tab shipped an unstyled
       * bare "x". */
      var closeBtn = tabs.length > 1 ? el('span', {
        class: 'synth-tabclose',
        title: 'Close Tab',
        onclick: function (ev) { ev.stopPropagation(); ev.preventDefault(); closeTab(i); }
      }, 'x') : null;

      var tabEl = el('div', {
        class: 'synth-tab' + (i === activeIndex ? ' active' : ''),
        title: t.url || 'New Tab',
        dataset: { tabIndex: String(i), tabId: t.id },
        onclick: function () { switchTab(i); },
        onmousedown: function (ev) { if (ev.button === 1) ev.preventDefault(); },
        onauxclick: function (ev) { if (ev.button === 1) { ev.preventDefault(); closeTab(i); } }
      },
        el('span', { class: 'synth-tab-label' }, truncate(t.title || 'New Tab', 26)),
        closeBtn
      );

      if (keepNew) strip.insertBefore(tabEl, keepNew);
      else strip.appendChild(tabEl);
    });
  }

  function newTab(url) {
    tabs.push(newTabObj());
    activeIndex = tabs.length - 1;
    renderTabs();
    return navigate(url || HOME_URL, { push: false });
  }

  function closeTab(i) {
    if (tabs.length <= 1) { setStatus('The last tab cannot be closed.'); return; }
    if (i < 0 || i >= tabs.length) return;
    tabs.splice(i, 1);
    if (activeIndex > i) activeIndex--;
    if (activeIndex >= tabs.length) activeIndex = tabs.length - 1;
    renderTabs();
    var t = currentTab();
    return navigate(t.url || HOME_URL, { push: false });
  }

  function switchTab(i) {
    if (i < 0 || i >= tabs.length || i === activeIndex) return;
    activeIndex = i;
    renderTabs();
    var t = currentTab();
    return navigate(t.url || HOME_URL, { push: false });
  }

  function syncHash(url, replace) {
    var target = '#' + url;
    if (location.hash === target) return;
    suppressHash++;
    try {
      if (replace && window.history && typeof history.replaceState === 'function') {
        history.replaceState(null, '', target);
      } else {
        location.hash = url;
      }
    } catch (e) {
      try { location.hash = url; } catch (e2) { /* ignore */ }
    }
    window.setTimeout(function () { if (suppressHash > 0) suppressHash--; }, 0);
  }

  function back() {
    var t = currentTab();
    if (!t.back.length) return;
    var url = t.back.pop();
    if (t.url) t.fwd.push(t.url);
    navigate(url, { push: false });
  }

  function forward() {
    var t = currentTab();
    if (!t.fwd.length) return;
    var url = t.fwd.pop();
    if (t.url) t.back.push(t.url);
    navigate(url, { push: false });
  }

  function refresh() {
    var t = currentTab();
    if (t.domain) SYNTH.data.forget(t.domain);
    navigate(t.url || HOME_URL, { push: false });
  }

  function stop() {
    navToken++;
    setProgress(false);
    setStatus('Stopped');
  }

  /* ================================================================== */
  /* BUILT-IN PAGES                                                      */
  /* ================================================================== */

  var TYPE_LABELS = {
    forum: 'Message Boards',
    social: 'Social Networks',
    blog: 'Weblogs',
    news: 'News',
    wiki: 'Encyclopedias & Reference',
    media: 'Video & Media',
    page: 'Homepages & Small Sites'
  };
  var TYPE_ORDER = ['forum', 'social', 'blog', 'news', 'wiki', 'media', 'page'];

  function builtinMount(extraClass) {
    return el('div', { class: 'synth-page synth-builtin ' + extraClass });
  }

  function engineLink(href, label, className) {
    var raw = String(href === null || href === undefined ? '' : href);
    var a = el('a', {
      class: className || 'synth-link',
      href: /^synth:\/\//i.test(raw) ? ('#' + raw) : '#',
      dataset: { synthHref: raw },
      title: raw
    });
    if (label && label.nodeType) a.appendChild(label);
    else a.appendChild(document.createTextNode(String(label === null || label === undefined ? raw : label)));
    return a;
  }

  function searchForm(initial) {
    var input = el('input', { type: 'text', name: 'q', value: initial || '', autocomplete: 'off' });
    var go = function (ev) {
      if (ev) { ev.preventDefault(); }
      var v = String(input.value || '').trim();
      if (v) navigate(searchUrl(v));
    };
    var form = el('form', { class: 'synth-b-form', onsubmit: go },
      input,
      el('button', { type: 'submit' }, 'Search')
    );
    return form;
  }

  function renderHomePage(mount, loc) {
    var list = registryList();
    mount.appendChild(el('div', { class: 'synth-b-head' },
      el('div', { class: 'synth-b-title' }, 'VerityNet Start Page'),
      el('div', { class: 'synth-b-sub' }, 'Your directory to the Verity County network — ' + list.length + ' sites indexed'),
      /* The number that says the quiet part. It drifts hourly, because a
       * figure that never moves is the tell that a page is a screenshot. */
      SYNTH.liveui
        ? el('div', { class: 'synth-b-stat' },
            SYNTH.liveui.automatedShare() + '% of VerityNet traffic in the last 24h was automated',
            el('span', { class: 'synth-b-stat-src' }, ' \u2014 VerityNet Transparency Report'))
        : null
    ));

    var body = el('div', { class: 'synth-b-body' });
    body.appendChild(searchForm(''));

    if (!SYNTH.data.registry) {
      body.appendChild(el('div', { class: 'synth-b-note' },
        el('div', null, el('b', null, 'The site index could not be loaded.')),
        el('div', null, 'net/registry.json was not found. If you opened this file directly, use the standalone build (which has everything inlined), or serve this folder from a local web server.')
      ));
    } else if (!list.length) {
      body.appendChild(el('div', { class: 'synth-b-note' }, 'The index loaded, but it lists no sites yet.'));
    }

    var groups = {};
    for (var i = 0; i < list.length; i++) {
      var t = String(list[i].type || 'page');
      if (!groups[t]) groups[t] = [];
      groups[t].push(list[i]);
    }

    var order = TYPE_ORDER.slice();
    for (var k in groups) if (hasOwn(groups, k) && order.indexOf(k) === -1) order.push(k);

    for (var o = 0; o < order.length; o++) {
      var type = order[o];
      var entries = groups[type];
      if (!entries || !entries.length) continue;
      entries.sort(function (a, b) {
        return String(a.title || a.domain).toLowerCase() < String(b.title || b.domain).toLowerCase() ? -1 : 1;
      });
      var group = el('div', { class: 'synth-b-group' },
        el('h2', null, (TYPE_LABELS[type] || type) + ' (' + entries.length + ')')
      );
      for (var e = 0; e < entries.length; e++) {
        var it = entries[e];
        group.appendChild(el('div', { class: 'synth-b-item' },
          engineLink('synth://' + it.domain + '/', it.title || it.domain, 'synth-link nm'),
          el('span', { class: 'dm' }, it.domain + (it.era ? ' · ' + it.era : '')),
          it.description ? el('span', { class: 'ds' }, it.description) : null
        ));
      }
      body.appendChild(group);
    }

    body.appendChild(el('div', { class: 'synth-b-foot' },
      'VerityNet Directory · no connection required · press Ctrl+T for a new tab'
    ));
    mount.appendChild(body);
    return 'VerityNet Start Page';
  }

  function escapeRe(s) {
    return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }

  function snippetNodes(text, terms) {
    var src = String(text || '');
    var lower = src.toLowerCase();
    var at = -1;
    for (var i = 0; i < terms.length; i++) {
      var p = lower.indexOf(terms[i]);
      if (p !== -1 && (at === -1 || p < at)) at = p;
    }
    var start = at === -1 ? 0 : Math.max(0, at - 70);
    var chunk = src.slice(start, start + 240);
    if (start > 0) chunk = '…' + chunk;
    if (start + 240 < src.length) chunk = chunk + '…';

    var nodes = [];
    if (!terms.length) { nodes.push(document.createTextNode(chunk)); return nodes; }
    var re;
    try { re = new RegExp('(' + terms.map(escapeRe).join('|') + ')', 'ig'); }
    catch (e) { nodes.push(document.createTextNode(chunk)); return nodes; }
    var last = 0, m;
    var guard = 0;
    while ((m = re.exec(chunk)) !== null && guard++ < 400) {
      if (m.index > last) nodes.push(document.createTextNode(chunk.slice(last, m.index)));
      nodes.push(el('b', null, m[0]));
      last = m.index + m[0].length;
      if (m[0].length === 0) re.lastIndex++;
    }
    if (last < chunk.length) nodes.push(document.createTextNode(chunk.slice(last)));
    return nodes;
  }

  /* ---- query-time snippets --------------------------------------------
     net/search.json carries no snippet text: a posting is an integer into
     its docs table.  We walk the site JSON (local, and already cached by
     SYNTH.data.getSite) to produce the snippet for the results we show.
     The walk mirrors the per-type document extraction in tools/build.py. */

  var SNIPPET_WIDTH = 140;
  var SNIPPET_RESULTS = 20;

  function mstrip(s) {
    if (typeof s !== 'string' || !s) return '';
    return (SYNTH.markup && SYNTH.markup.strip) ? SYNTH.markup.strip(s) : s;
  }

  function joinText(parts) {
    var out = [];
    for (var i = 0; i < parts.length; i++) {
      var p = parts[i], s;
      if (typeof p === 'string') { s = mstrip(p); if (s) out.push(s); }
      else if (Array.isArray(p)) { s = joinText(p); if (s) out.push(s); }
    }
    return out.join(' ');
  }

  function fieldsOf(rows, key) {
    var out = [];
    for (var i = 0; i < (rows || []).length; i++) {
      var r = rows[i];
      if (r && typeof r === 'object' && typeof r[key] === 'string') out.push(r[key]);
    }
    return out;
  }

  function findBy(rows, key, value) {
    for (var i = 0; i < (rows || []).length; i++) {
      var r = rows[i];
      if (r && typeof r === 'object' && String(r[key]) === value) return r;
    }
    return null;
  }

  function blockText(block) {
    if (!block || typeof block !== 'object') return '';
    var k = block.kind, rows;
    if (k === 'heading' || k === 'marquee') return joinText([block.text]);
    if (k === 'text') return joinText([block.body]);
    if (k === 'list') return joinText([block.items]);
    if (k === 'table') return joinText([block.head, block.rows]);
    if (k === 'image') return joinText([block.caption]);
    if (k === 'guestbook') {
      rows = block.entries || [];
      return joinText([fieldsOf(rows, 'author'), fieldsOf(rows, 'body')]);
    }
    if (k === 'webring') {
      rows = block.members || [];
      return joinText([block.ringName, fieldsOf(rows, 'label'), fieldsOf(rows, 'domain')]);
    }
    return '';
  }

  function pageText(data, id) {
    var page = findBy(data.pages, 'id', id);
    if (!page) return '';
    var out = [];
    var blocks = page.blocks || [];
    for (var i = 0; i < blocks.length; i++) {
      var s = blockText(blocks[i]);
      if (s) out.push(s);
    }
    return out.join(' ');
  }

  function docText(site, path) {
    if (!site || typeof site !== 'object') return '';
    var data = (site.data && typeof site.data === 'object') ? site.data : {};
    var p = String(path || '/');
    var row, kids, i;

    if (p === '/') {
      return joinText([site.description, site.era,
                       pageText(data, 'index') || pageText(data, 'home')]);
    }

    var seg = p.replace(/^\/+/, '').split('/');
    var kind = seg[0];
    var id = '';
    if (seg.length > 1) {
      try { id = decodeURIComponent(seg.slice(1).join('/')); }
      catch (e) { id = seg.slice(1).join('/'); }
    }

    if (kind === 'board' && id) {
      var cats = data.categories || [];
      for (i = 0; i < cats.length; i++) {
        if (!cats[i] || typeof cats[i] !== 'object') continue;
        row = findBy(cats[i].boards, 'id', id);
        if (row) return joinText([row.desc, cats[i].name]);
      }
      return '';
    }
    if (kind === 'topic' && id) {
      row = findBy(data.topics, 'id', id);
      if (!row) return '';
      kids = row.posts || [];
      return joinText([row.author, fieldsOf(kids, 'author'),
                       fieldsOf(kids, 'body'), fieldsOf(kids, 'signature')]);
    }
    if (kind === 'user' && id) {
      var prof = (data.profile && typeof data.profile === 'object') ? data.profile : null;
      if (prof && String(prof.handle) === id) {
        return joinText([prof.bio, prof.location, prof.mood]);
      }
      row = findBy(data.friends, 'handle', id);
      return row ? joinText([row.displayName, row.handle]) : '';
    }
    if (kind === 'post' && id) {
      row = findBy(data.feed, 'id', id);
      if (row) {
        kids = row.replies || [];
        return joinText([row.body, fieldsOf(kids, 'author'),
                         fieldsOf(kids, 'handle'), fieldsOf(kids, 'body')]);
      }
      row = findBy(data.posts, 'id', id);
      if (row) {
        kids = row.comments || [];
        return joinText([row.body, row.tags,
                         fieldsOf(kids, 'author'), fieldsOf(kids, 'body')]);
      }
      return '';
    }
    if (kind === 'tag' && id) return joinText([id, data.author]);
    if (kind === 'section' && id) {
      row = findBy(data.sections, 'id', id);
      return row ? joinText([row.name]) : '';
    }
    if (kind === 'article' && id) {
      row = findBy(data.articles, 'id', id);
      return row ? joinText([row.dek, row.byline, row.lead, row.body]) : '';
    }
    if (kind === 'wiki' && id) {
      row = findBy(data.articles, 'id', id);
      if (!row) return '';
      var info = (row.infobox && typeof row.infobox === 'object') ? row.infobox : {};
      var cells = [];
      var irows = info.rows || [];
      for (i = 0; i < irows.length; i++) {
        if (Array.isArray(irows[i])) cells = cells.concat(irows[i]);
      }
      kids = row.sections || [];
      return joinText([row.summary, info.caption, cells,
                       fieldsOf(kids, 'heading'), fieldsOf(kids, 'body')]);
    }
    if (kind === 'category' && id) {
      row = findBy(data.categories, 'id', id);
      return row ? joinText([row.name]) : '';
    }
    if (kind === 'channel' && id) {
      row = findBy(data.channels, 'id', id);
      return row ? joinText([row.about]) : '';
    }
    if (kind === 'watch' && id) {
      row = findBy(data.items, 'id', id);
      if (!row) return '';
      kids = row.comments || [];
      return joinText([row.description, row.uploader,
                       fieldsOf(kids, 'author'), fieldsOf(kids, 'body')]);
    }
    /* --- the 2026 types ------------------------------------------------
     *
     * These must mirror the builders in tools/build.py. build.py decides
     * what is *findable*; this decides what the result *says*. For a long
     * time neither existed for any of these types, so eleven site types were
     * unsearchable; adding only the build side would have made them findable
     * with a blank snippet under every hit, which reads as a broken index. */

    if (kind === 'item' && id) {                       /* aggregator */
      row = findBy(data.links, 'id', id);
      if (!row) return '';
      var cbodies = [], cauthors = [];
      (function walk(rows) {
        for (var k = 0; k < (rows || []).length; k++) {
          var c = rows[k];
          if (!c || typeof c !== 'object') continue;
          cbodies.push(c.body); cauthors.push(c.by);
          walk(c.replies);
        }
      }(row.comments));
      return joinText([row.by, row.domain, cauthors, cbodies]);
    }
    if (kind === 'q' && id) {                          /* qa */
      row = findBy(data.questions, 'id', id);
      if (!row) return '';
      kids = row.answers || [];
      var qcom = row.comments || [];
      return joinText([row.body, row.by, row.closedReason,
                       fieldsOf(kids, 'by'), fieldsOf(kids, 'body'),
                       fieldsOf(qcom, 'by'), fieldsOf(qcom, 'body')]);
    }
    if (kind === 't' && id) {                          /* board */
      row = findBy(data.threads, 'id', id);
      if (!row) return '';
      kids = row.posts || [];
      return joinText([row.body, row.by,
                       fieldsOf(kids, 'by'), fieldsOf(kids, 'body')]);
    }
    if (kind === 'p' && id) {                          /* shop product */
      row = findBy(data.products, 'id', id);
      if (!row) return '';
      kids = row.reviews || [];
      return joinText([row.blurb, row.bullets, row.seller,
                       fieldsOf(kids, 'by'), fieldsOf(kids, 'title'),
                       fieldsOf(kids, 'body')]);
    }
    if (kind === 'l' && id) {                          /* market listing */
      row = findBy(data.listings, 'id', id);
      return row ? joinText([row.body, row.by, row.price, row.condition]) : '';
    }
    if (kind === 'chat') {                             /* assistant */
      kids = data.canned || [];
      return joinText([data.tagline, data.model, data.disclaimers,
                       data.suggested, fieldsOf(kids, 'q'), fieldsOf(kids, 'a')]);
    }
    if (kind === 'f' && id) {                          /* mail folder */
      row = findBy(data.folders, 'id', id);
      return row ? joinText([row.name]) : '';
    }
    if (kind === 'm' && id) {                          /* mail message */
      row = findBy(data.messages, 'id', id);
      return row ? joinText([row.body, row.from, row.fromAddr]) : '';
    }
    if (kind === 's' && id) {                          /* portal service */
      row = findBy(data.services, 'id', id);
      if (!row) return '';
      kids = row.forms || [];
      return joinText([row.blurb, row.status, row.steps,
                       fieldsOf(kids, 'name'), fieldsOf(kids, 'note')]);
    }
    if (kind === 'w' && id) {                          /* stream video */
      row = findBy(data.videos, 'id', id);
      if (!row) return '';
      kids = row.comments || [];
      return joinText([row.description,
                       fieldsOf(kids, 'by'), fieldsOf(kids, 'body')]);
    }
    if (kind === 'c' && id) {
      /* /c/ is three different things: a stream channel, a shop category and
       * a market category. Try each; only one will have the id. */
      row = findBy(data.channels, 'id', id);
      if (row) return joinText([row.about, row.name]);
      row = findBy(data.categories, 'id', id) || findBy(data.cats, 'id', id);
      return row ? joinText([row.name]) : '';
    }

    /* "page" sites address their pages as /<pageId> */
    return pageText(data, seg.join('/'));
  }

  function cutSnippet(text, terms) {
    var src = String(text || '');
    if (!src) return '';
    var lower = src.toLowerCase();
    var at = -1;
    for (var i = 0; i < terms.length; i++) {
      var p = lower.indexOf(terms[i]);
      if (p !== -1 && (at === -1 || p < at)) at = p;
    }
    var start = at === -1 ? 0 : Math.max(0, at - Math.floor(SNIPPET_WIDTH / 3));
    var end = Math.min(src.length, start + SNIPPET_WIDTH);
    var piece = src.slice(start, end).replace(/\s+/g, ' ').trim();
    if (!piece) return '';
    if (start > 0) piece = '…' + piece;
    if (end < src.length) piece = piece + '…';
    return piece;
  }

  function fallbackText(rec) {
    var entry = registryEntry(rec.domain);
    return String((entry && entry.description) || rec.title || rec.domain || '');
  }

  function attachSnippets(results, terms) {
    var top = results.slice(0, SNIPPET_RESULTS);
    var domains = [];
    var seen = {};
    var i;
    for (i = 0; i < top.length; i++) {
      if (hasOwn(seen, top[i].domain)) continue;
      seen[top[i].domain] = 1;
      domains.push(top[i].domain);
    }
    var jobs = [];
    for (i = 0; i < domains.length; i++) jobs.push(getSite(domains[i]));

    function finish(sites) {
      var map = {};
      var j;
      for (j = 0; j < domains.length; j++) map[domains[j]] = (sites && sites[j]) || null;
      for (j = 0; j < top.length; j++) {
        var rec = top[j];
        var site = hasOwn(map, rec.domain) ? map[rec.domain] : null;
        rec.text = cutSnippet(site ? docText(site, rec.path) : '', terms) || fallbackText(rec);
      }
      for (j = top.length; j < results.length; j++) {
        results[j].text = fallbackText(results[j]);
      }
      return results;
    }

    return Promise.all(jobs).then(finish, function () { return finish(null); });
  }

  function loadSearchIndex() {
    if (searchPromise) return searchPromise;
    var emb = embedded();
    if (emb && emb.search) {
      searchPromise = Promise.resolve(emb.search);
      return searchPromise;
    }
    if (emb) {
      searchPromise = Promise.resolve(null);
      return searchPromise;
    }
    searchPromise = fetchJSON('./net/search.json');
    return searchPromise;
  }

  function normIndex(raw) {
    if (!raw || typeof raw !== 'object') return null;
    if (!Array.isArray(raw.docs) || !raw.terms || typeof raw.terms !== 'object') return null;
    return raw;
  }

  /* every posting list for one query term: the exact token plus any token it
     is a prefix of, so "grid" still finds "gridfall". */
  function postingsFor(idx, term) {
    var out = [];
    var map = idx.terms;
    var k;
    if (hasOwn(map, term) && Array.isArray(map[term])) out.push(map[term]);
    for (k in map) {
      if (!hasOwn(map, k) || k === term) continue;
      if (k.length > term.length && k.indexOf(term) === 0 && Array.isArray(map[k])) out.push(map[k]);
    }
    return out;
  }

  function search(q) {
    var query = String(q === null || q === undefined ? '' : q).trim();
    var terms = query.toLowerCase().split(/\s+/).filter(function (t) { return !!t; });
    return loadRegistry().then(loadSearchIndex).then(function (raw) {
      if (!terms.length) return [];
      var idx = normIndex(raw);
      var hits = [];
      var out = [];
      var i, t, j, k;

      if (idx) {
        for (t = 0; t < terms.length; t++) {
          var lists = postingsFor(idx, terms[t]);
          var touched = {};
          for (j = 0; j < lists.length; j++) {
            var list = lists[j];
            for (k = 0; k < list.length; k++) {
              var n = list[k];
              if (typeof n !== 'number' || n < 0 || n >= idx.docs.length) continue;
              var h = hits[n];
              if (!h) { h = hits[n] = { matched: 0, postings: 0 }; }
              h.postings++;
              if (!touched[n]) { touched[n] = 1; h.matched++; }
            }
          }
        }
        for (i = 0; i < idx.docs.length; i++) {
          if (!hits[i]) continue;
          var doc = idx.docs[i];
          if (!doc || typeof doc !== 'object') continue;
          var domain = String(doc.d || '').toLowerCase();
          if (!domain) continue;
          var path = String(doc.p || '/');
          if (path.charAt(0) !== '/') path = '/' + path;
          var entry = registryEntry(domain);
          out.push({
            domain: domain,
            path: path,
            url: 'synth://' + domain + path,
            title: String(doc.t || path),
            text: '',
            type: String((entry && entry.type) || ''),
            matched: hits[i].matched,
            postings: hits[i].postings
          });
        }
      }

      /* always fold the registry in, so every site front page is findable
         even by its domain, which the index does not tokenise */
      var reg = registryList();
      for (i = 0; i < reg.length; i++) {
        var site = reg[i];
        var dom = String(site.domain || '').toLowerCase();
        if (!dom) continue;
        var hay = (dom + ' ' + String(site.title || '') + ' ' + String(site.description || '')).toLowerCase();
        var count = 0;
        for (t = 0; t < terms.length; t++) if (hay.indexOf(terms[t]) !== -1) count++;
        if (!count) continue;
        out.push({
          domain: dom,
          path: '/',
          url: 'synth://' + dom + '/',
          title: String(site.title || dom),
          text: '',
          type: String(site.type || ''),
          matched: count,
          postings: 0
        });
      }

      out.sort(function (a, b) {
        if (b.matched !== a.matched) return b.matched - a.matched;
        return b.postings - a.postings;
      });
      var seen = {};
      var dedup = [];
      for (k = 0; k < out.length; k++) {
        if (seen[out[k].url]) continue;
        seen[out[k].url] = 1;
        dedup.push(out[k]);
      }
      return attachSnippets(dedup.slice(0, 80), terms);
    });
  }

  function renderSearchPage(mount, query, results) {
    var terms = String(query || '').toLowerCase().split(/\s+/).filter(function (t) { return !!t; });

    mount.appendChild(el('div', { class: 'synth-b-head' },
      el('div', { class: 'synth-b-title' }, 'Verity Search'),
      el('div', { class: 'synth-b-sub' }, 'Searching the whole of VerityNet, offline')
    ));

    var body = el('div', { class: 'synth-b-body' });
    body.appendChild(searchForm(query));

    if (!query) {
      body.appendChild(el('div', { class: 'synth-b-note' }, 'Type something above to search every page on the network.'));
      mount.appendChild(body);
      return 'Verity Search';
    }

    body.appendChild(el('div', { class: 'synth-b-count' },
      results.length
        ? ('Results ' + (results.length === 1 ? '1 - 1' : '1 - ' + results.length) + ' of about ' + results.length + ' for "' + query + '"')
        : ('Your search - "' + query + '" - did not match any documents.')
    ));

    if (!results.length) {
      body.appendChild(el('div', null,
        el('div', null, 'Suggestions:'),
        el('ul', null,
          el('li', null, 'Make sure all words are spelled correctly.'),
          el('li', null, 'Try different keywords, or fewer of them.'),
          el('li', null, 'Browse the ', engineLink(HOME_URL, 'start page directory'), ' instead.')
        )
      ));
    }

    for (var i = 0; i < results.length; i++) {
      var r = results[i];
      var snip = el('div', { class: 's' });
      var nodes = snippetNodes(r.text || r.title, terms);
      for (var n = 0; n < nodes.length; n++) snip.appendChild(nodes[n]);
      body.appendChild(el('div', { class: 'synth-b-result' },
        el('div', { class: 't' }, engineLink(r.url, r.title || r.url)),
        snip,
        el('div', { class: 'u' }, r.url + (r.type ? '  -  ' + r.type : ''))
      ));
    }

    body.appendChild(el('div', { class: 'synth-b-foot' }, 'Verity Search · index built offline · no results were harmed'));
    mount.appendChild(body);
    return 'Verity Search: ' + query;
  }

  function renderNotFound(mount, loc) {
    var domain = loc.domain || '(none)';
    var box = el('div', { class: 'synth-b-err' },
      el('h1', null, 'The page cannot be displayed'),
      el('div', null, 'The page you are looking for is currently unavailable. The site might be experiencing technical difficulties, or you may need to adjust your browser settings.'),
      el('div', { class: 'synth-b-rule' }),
      el('div', null, el('b', null, 'Cannot find server or DNS Error')),
      el('div', null, 'Verity Explorer could not find ', el('b', null, domain), ' on this network.'),
      el('div', { class: 'synth-b-rule' }),
      el('div', null, 'Please try the following:'),
      el('ul', null,
        el('li', null, 'Check that the address ', el('b', null, formatLoc(loc)), ' is spelled correctly.'),
        el('li', null, 'Click the Refresh button, or try again later.'),
        el('li', null, 'Go back to the ', engineLink(HOME_URL, 'VerityNet start page'), ' and pick a site from the directory.'),
        el('li', null, 'Search for ', engineLink(searchUrl(domain), '"' + domain + '"'), ' on Verity Search.')
      ),
      el('div', { class: 'synth-b-rule' }),
      el('div', { class: 'synth-b-foot' }, 'Cannot find server or DNS Error · Verity Explorer')
    );
    mount.appendChild(box);
    return 'Cannot find server';
  }

  function renderNoRegistry(mount, loc) {
    var box = el('div', { class: 'synth-b-err' },
      el('h1', null, 'The network index is missing'),
      el('div', null, 'Verity Explorer loaded, but it could not read ', el('b', null, 'net/registry.json'), ', so it does not know which sites exist.'),
      el('div', { class: 'synth-b-note' },
        el('div', null, el('b', null, 'Two ways to fix this:')),
        el('ul', null,
          el('li', null, 'Run the build tool to regenerate the index, then reload.'),
          el('li', null, 'Or open the single-file standalone build, which carries every site inside it and needs no files beside it.')
        )
      ),
      el('div', null, 'Requested address: ', el('b', null, formatLoc(loc))),
      el('div', { class: 'synth-b-foot' }, 'Nothing was fetched from anywhere. This browser never goes online.')
    );
    mount.appendChild(box);
    return 'Network index missing';
  }

  /* ================================================================== */
  /* NAVIGATION                                                          */
  /* ================================================================== */

  function commit(loc, mount, titleStr, opts, tab) {
    var vp = ensureViewport();
    clearNode(vp);
    vp.appendChild(mount);
    try { vp.scrollTop = 0; } catch (e) { /* ignore */ }
    try { window.scrollTo(0, 0); } catch (e2) { /* ignore */ }

    var full = formatLoc(loc);
    if (opts.push !== false) {
      if (tab.url && tab.url !== full) {
        tab.back.push(tab.url);
        if (tab.back.length > MAX_STACK) tab.back.shift();
      }
      tab.fwd.length = 0;
    }
    tab.url = full;
    tab.domain = loc.domain;
    tab.title = titleStr || full;

    setAddress(full);
    document.title = (titleStr ? titleStr + ' - ' : '') + BROWSER_NAME;
    renderTabs();
    updateNavButtons();
    syncHash(full, opts.push === false);
    setProgress(false);
    setStatus('Done');

    /* Record the visit. This is the single choke point every successful
     * navigation passes through with a domain in hand, which makes it the
     * one place "when did you last look at this" can live without threading
     * it through every renderer.
     *
     * The stream ledger goes with it: whatever the page just asked
     * live.stream() for IS what that site watches, so the unread count is
     * derived from what the renderer really did rather than from a table of
     * stream keys kept in sync by hand. See app/alerts.js.
     *
     * Skipped for the app's own pages -- being "behind" on your own settings
     * panel is not a thing. */
    if (SYNTH.alerts && SYNTH.alerts.markVisited && loc.domain &&
        loc.domain !== HOME_DOMAIN && loc.domain !== SEARCH_DOMAIN &&
        loc.domain !== FEEDS_DOMAIN) {
      var feeds = (SYNTH.live && SYNTH.live.ledgerRows) ? SYNTH.live.ledgerRows() : [];
      try { SYNTH.alerts.markVisited(loc.domain, feeds); } catch (e) { /* not fatal */ }
    }

    if (SYNTH.feedsui && SYNTH.feedsui.paintBadge) {
      try { SYNTH.feedsui.paintBadge(); } catch (e) { /* not fatal */ }
    }

    /* Hand the Android app the small part it cannot derive for itself, so
     * the home-screen widget keeps counting with the app closed. A no-op
     * anywhere that is not the app. */
    if (SYNTH.host && SYNTH.host.sync) {
      try { SYNTH.host.sync(); } catch (e) { /* not fatal */ }
    }
  }

  function navigate(url, opts) {
    opts = opts || {};
    var tab = currentTab();
    var loc = resolve(url, tab.domain || HOME_DOMAIN);
    if (!loc.domain) loc.domain = HOME_DOMAIN;
    var full = formatLoc(loc);
    var token = ++navToken;

    setProgress(true);
    setStatus('Opening ' + full + ' …');
    setAddress(full);

    return loadRegistry().then(function () {
      if (token !== navToken) return null;

      if (loc.domain === HOME_DOMAIN) {
        var homeMount = builtinMount('synth-startpage');
        var ht = renderHomePage(homeMount, loc);
        commit(loc, homeMount, ht, opts, tab);
        return null;
      }

      if (loc.domain === FEEDS_DOMAIN) {
        /* Feeds is a page rather than a dropdown so it gets history, the
         * back button and the phone layout for nothing -- and the command
         * bar it hangs off is hidden below 700px, so a dropdown there would
         * be unreachable on the primary target. Drawn by app/feedsui.js. */
        var fm = builtinMount('synth-feedspage');
        var ft = (SYNTH.feedsui && SYNTH.feedsui.render)
          ? SYNTH.feedsui.render(fm, loc)
          : 'Feeds';
        commit(loc, fm, ft, opts, tab);
        return null;
      }

      if (loc.domain === SEARCH_DOMAIN) {
        var q = loc.query && loc.query.q ? loc.query.q : '';
        return search(q).then(function (results) {
          if (token !== navToken) return null;
          var sm = builtinMount('synth-searchpage');
          var st = renderSearchPage(sm, q, results || []);
          commit(loc, sm, st, opts, tab);
          return null;
        }, function () {
          if (token !== navToken) return null;
          var sm2 = builtinMount('synth-searchpage');
          var st2 = renderSearchPage(sm2, q, []);
          commit(loc, sm2, st2, opts, tab);
          return null;
        });
      }

      return getSite(loc.domain).then(function (site) {
        if (token !== navToken) return null;

        if (!site) {
          var errMount = builtinMount('synth-errorpage');
          var et = (!SYNTH.data.registry && !embedded())
            ? renderNoRegistry(errMount, loc)
            : renderNotFound(errMount, loc);
          commit(loc, errMount, et, opts, tab);
          return null;
        }

        var mount = el('div', {
          class: 'synth-page skin-' + (site.skin || 'plain-white'),
          dataset: { domain: loc.domain, type: site.type || '' }
        });

        var pageTitle = site.title || loc.domain;

        /* Clear the arrivals ledger immediately before the renderer runs, so
         * whatever it asks live.stream() for becomes the record of what THIS
         * page is watching. app/tick.js compares against it to say how many
         * things have arrived since. */
        if (SYNTH.live && SYNTH.live.resetLedger) SYNTH.live.resetLedger();
        if (SYNTH.tick && SYNTH.tick.reset) SYNTH.tick.reset();

        var ctx = {
          site: site,
          path: loc.path,
          query: loc.query,
          mount: mount,
          el: SYNTH.el,
          markup: function (text) {
            return (SYNTH.markup && SYNTH.markup.parse)
              ? SYNTH.markup.parse(text)
              : document.createDocumentFragment();
          },
          link: function (href, label, className) { return engineLink(href, label, className); },
          title: function (s) { if (s) pageTitle = String(s); }
        };

        SYNTH.render.render(ctx);
        if (token !== navToken) return null;
        commit(loc, mount, pageTitle, opts, tab);
        return null;
      });
    }).then(null, function (err) {
      if (window.console && console.error) console.error('[synth.engine] navigation failed', err && err.stack ? err.stack : err);
      if (token !== navToken) return null;
      var m = builtinMount('synth-errorpage');
      renderNotFound(m, loc);
      commit(loc, m, 'Cannot find server', opts, tab);
      return null;
    });
  }

  /* ================================================================== */
  /* INPUT WIRING                                                        */
  /* ================================================================== */

  function isKnownDomain(d) {
    d = String(d || '').toLowerCase();
    if (d === HOME_DOMAIN || d === SEARCH_DOMAIN || d === FEEDS_DOMAIN) return true;
    return !!registryEntry(d);
  }

  function normalizeTyped(v) {
    v = String(v || '').trim();
    if (!v) return HOME_URL;
    if (/^synth:\/\//i.test(v)) return v;
    if (v.charAt(0) === '#') return v.slice(1);
    if (v.charAt(0) === '/') return v;
    var head = v.split('/')[0].split('?')[0];
    if (head.indexOf('.') !== -1) return 'synth://' + v;
    if (isKnownDomain(head)) return 'synth://' + v;
    return searchUrl(v);
  }

  function addressGo() {
    if (!ui.address) return;
    var v = String(ui.address.value === undefined ? ui.address.textContent : ui.address.value || '').trim();
    if (!v) return;
    navigate(normalizeTyped(v));
  }

  function focusAddress() {
    if (!ui.address) return;
    try { ui.address.focus(); if (ui.address.select) ui.address.select(); } catch (e) { /* ignore */ }
  }

  function hoverUrlOf(a) {
    var raw = null;
    if (a.getAttribute && a.getAttribute('data-synth-href') !== null) raw = a.getAttribute('data-synth-href');
    else if (a.getAttribute) {
      var h = a.getAttribute('href') || '';
      if (/^#?synth:\/\//i.test(h) || h.charAt(0) === '/') raw = h.replace(/^#/, '');
    }
    if (raw === null) return null;
    return formatLoc(resolve(raw, currentTab().domain || HOME_DOMAIN));
  }

  function wireViewport() {
    var vp = ensureViewport();

    vp.addEventListener('click', function (ev) {
      var a = closestTag(ev.target, 'a');
      if (!a) return;
      var raw = a.getAttribute ? a.getAttribute('data-synth-href') : null;
      if (raw === null && a.getAttribute) {
        var h = a.getAttribute('href') || '';
        if (/^#?synth:\/\//i.test(h) || (h.charAt(0) === '/' && h.charAt(1) !== '/')) raw = h.replace(/^#/, '');
      }
      if (raw === null) return;
      ev.preventDefault();
      navigate(raw);
    }, false);

    vp.addEventListener('mouseover', function (ev) {
      var a = closestTag(ev.target, 'a');
      if (!a) return;
      var u = hoverUrlOf(a);
      if (u) setStatus(u);
    }, false);

    vp.addEventListener('mouseout', function (ev) {
      var a = closestTag(ev.target, 'a');
      if (!a) return;
      setStatus('Done');
    }, false);
  }

  function wireChrome() {
    ui.progress = pick('#synth-progress', '.synth-progress');
    ui.address = pick('#synth-address', '.synth-address');
    ui.back = pick('#synth-back', '.synth-back');
    ui.forward = pick('#synth-forward', '.synth-forward');
    /* There are two Home buttons and neither is called '#synth-home'. The
     * command bar has '#synth-cmd-home' and the nav row has '#synth-navhome'
     * -- and the command bar is hidden below 700px (aero.css:1096), which
     * makes the nav-row one *the* Home button on a phone. This used to look
     * for a selector nothing matched, so ui.home was null, no listener was
     * attached, and Home did nothing at all on the primary target. Collect
     * every one that exists rather than picking one. */
    ui.homes = [];
    ['#synth-navhome', '#synth-cmd-home', '#synth-home', '.synth-home'].forEach(function (sel) {
      var node = pick(sel);
      if (node && ui.homes.indexOf(node) === -1) ui.homes.push(node);
    });
    ui.go = pick('#synth-go', '.synth-go');
    ui.newtab = pick('#synth-newtab', '.synth-newtab');
    ui.searchBox = pick('#synth-search', '.synth-search');
    ui.refresh = pick('#synth-refresh', '.synth-refresh');
    ui.stop = pick('#synth-stop', '.synth-stop');

    if (ui.back) ui.back.addEventListener('click', function (e) { e.preventDefault(); back(); }, false);
    if (ui.forward) ui.forward.addEventListener('click', function (e) { e.preventDefault(); forward(); }, false);
    ui.homes.forEach(function (node) {
      node.addEventListener('click', function (e) { e.preventDefault(); navigate(HOME_URL); }, false);
    });

    /* The Feeds button has existed in index.html since the first commit and
     * has never been wired to anything. */
    ui.feeds = pick('#synth-cmd-feeds', '.synth-cmd-feeds');
    if (ui.feeds) {
      ui.feeds.addEventListener('click', function (e) {
        e.preventDefault();
        navigate('synth://' + FEEDS_DOMAIN + '/');
      }, false);
    }
    if (ui.go) ui.go.addEventListener('click', function (e) { e.preventDefault(); addressGo(); }, false);
    if (ui.newtab) ui.newtab.addEventListener('click', function (e) { e.preventDefault(); newTab(); }, false);
    if (ui.refresh) ui.refresh.addEventListener('click', function (e) { e.preventDefault(); refresh(); }, false);
    if (ui.stop) ui.stop.addEventListener('click', function (e) { e.preventDefault(); stop(); }, false);

    if (ui.address) {
      ui.address.addEventListener('keydown', function (e) {
        if (e.key === 'Enter' || e.keyCode === 13) { e.preventDefault(); addressGo(); }
      }, false);
      var form = closestTag(ui.address, 'form');
      if (form) form.addEventListener('submit', function (e) { e.preventDefault(); addressGo(); }, false);
    }

    if (ui.searchBox) {
      var tag = ui.searchBox.tagName ? ui.searchBox.tagName.toUpperCase() : '';
      if (tag === 'INPUT' || tag === 'TEXTAREA') {
        ui.searchBox.addEventListener('keydown', function (e) {
          if (e.key === 'Enter' || e.keyCode === 13) {
            e.preventDefault();
            var v = String(ui.searchBox.value || '').trim();
            navigate(v ? searchUrl(v) : ('synth://' + SEARCH_DOMAIN + '/'));
          }
        }, false);
        var sform = closestTag(ui.searchBox, 'form');
        if (sform) {
          sform.addEventListener('submit', function (e) {
            e.preventDefault();
            var v = String(ui.searchBox.value || '').trim();
            navigate(v ? searchUrl(v) : ('synth://' + SEARCH_DOMAIN + '/'));
          }, false);
        }
        var sgo = pick('#synth-searchgo', '.synth-searchgo');
        if (sgo) {
          sgo.addEventListener('click', function (e) {
            e.preventDefault();
            var v = String(ui.searchBox.value || '').trim();
            navigate(v ? searchUrl(v) : ('synth://' + SEARCH_DOMAIN + '/'));
          }, false);
        }
      } else {
        ui.searchBox.addEventListener('click', function (e) {
          e.preventDefault();
          var box = pick('#synth-searchbox', '.synth-searchbox');
          var v = box && box.value ? String(box.value).trim() : '';
          navigate(v ? searchUrl(v) : ('synth://' + SEARCH_DOMAIN + '/'));
        }, false);
      }
    }

    document.addEventListener('keydown', function (ev) {
      var k = ev.key || '';
      var inField = false;
      var tgt = ev.target;
      if (tgt && tgt.tagName) {
        var tn = tgt.tagName.toUpperCase();
        inField = (tn === 'INPUT' || tn === 'TEXTAREA' || tn === 'SELECT');
      }

      if (ev.altKey && !ev.ctrlKey && !ev.metaKey && (k === 'ArrowLeft' || ev.keyCode === 37)) {
        ev.preventDefault(); back(); return;
      }
      if (ev.altKey && !ev.ctrlKey && !ev.metaKey && (k === 'ArrowRight' || ev.keyCode === 39)) {
        ev.preventDefault(); forward(); return;
      }
      if ((ev.ctrlKey || ev.metaKey) && (k === 't' || k === 'T')) { ev.preventDefault(); newTab(); return; }
      if ((ev.ctrlKey || ev.metaKey) && (k === 'w' || k === 'W')) { ev.preventDefault(); closeTab(activeIndex); return; }
      if ((ev.ctrlKey || ev.metaKey) && (k === 'l' || k === 'L')) { ev.preventDefault(); focusAddress(); return; }
      if (k === 'F5' || ev.keyCode === 116) { ev.preventDefault(); refresh(); return; }
      if (k === 'Escape' || ev.keyCode === 27) {
        stop();
        if (inField && tgt.blur) tgt.blur();
        return;
      }
    }, false);

    window.addEventListener('hashchange', function () {
      if (suppressHash > 0) { suppressHash--; return; }
      var h = String(location.hash || '').replace(/^#/, '');
      if (!h) return;
      var t = currentTab();
      if (t.url === h) return;
      if (t.back.length && t.back[t.back.length - 1] === h) {
        t.back.pop();
        if (t.url) t.fwd.push(t.url);
      } else if (t.fwd.length && t.fwd[t.fwd.length - 1] === h) {
        t.fwd.pop();
        if (t.url) t.back.push(t.url);
      }
      navigate(h, { push: false });
    }, false);
  }

  /* ================================================================== */
  /* BOOT                                                                */
  /* ================================================================== */

  function boot() {
    injectBuiltinCSS();
    ensureViewport();
    ensureTabStrip();
    ensureStatus();
    wireChrome();
    wireViewport();

    tabs = [newTabObj()];
    activeIndex = 0;
    renderTabs();
    updateNavButtons();
    setStatus('Ready');

    var h = String(location.hash || '').replace(/^#/, '');
    var start = /^synth:\/\//i.test(h) ? h : HOME_URL;

    /* The heartbeat. Until this existed the page painted once and froze, so
     * the network moved between visits and was a still photograph during
     * one. See app/tick.js for what it does and, more importantly, for what
     * it deliberately does not. */
    if (SYNTH.tick && SYNTH.tick.start) SYNTH.tick.start();

    /* Wait for storage before the first render.
     *
     * Renderers build DOM synchronously and cannot await, so they read the
     * account straight out of the in-memory mirror. IndexedDB opens
     * asynchronously, so a cold start used to draw the first page before the
     * mirror was filled: your account looked missing, the composer offered to
     * sign you up again, and your own posts were absent -- until you navigated
     * once, at which point everything reappeared. Nothing was lost, but it
     * read exactly like data loss, which is worse.
     *
     * Storage failing is not a reason to show nothing, so the failure path
     * navigates anyway and the site runs in its logged-out state. */
    if (SYNTH.store && SYNTH.store.ready) {
      var go = function () { navigate(start, { push: false }); };
      var ready = SYNTH.store.ready();
      var settled = false;
      var once = function () { if (!settled) { settled = true; go(); } };
      if (ready && typeof ready.then === 'function') {
        ready.then(function () {
          return (SYNTH.me && SYNTH.me.ready) ? SYNTH.me.ready() : null;
        }).then(once, once);
        /* Belt and braces: a storage layer that never settles must not leave
         * the app on a blank screen forever. */
        setTimeout(once, 3000);
      } else {
        go();
      }
    } else {
      navigate(start, { push: false });
    }
  }

  SYNTH.engine = {
    navigate: navigate,
    back: back,
    forward: forward,
    refresh: refresh,
    stop: stop,
    search: search,
    resolve: resolve,
    format: formatLoc,
    home: function () { return navigate(HOME_URL); },
    newTab: newTab,
    closeTab: closeTab,
    switchTab: switchTab,
    tabs: function () { return tabs.slice(); },
    HOME_URL: HOME_URL,
    SEARCH_DOMAIN: SEARCH_DOMAIN,
    HOME_DOMAIN: HOME_DOMAIN
  };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot, false);
  } else {
    window.setTimeout(boot, 0);
  }
})();
